server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: 1234
  jpa:
    open-in-view: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hightlight_sql: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] -%msg%n"
#  level:
#      org:
#          hibernate:
#            type.descriptor.sql: TRACE
#            SQL: DEBUG

restapi:
  kakao:
    baseUrl: https://dapi.kakao.com
    key: 55141a520bff563c05dbe3b445d36f04

